**Disney Dataset Creation**

In [56]:
import requests
from bs4 import BeautifulSoup as bs

## Task#1 : Get Info Box Toy Story 3(Store in Python Dictionary)

In [57]:
r = requests.get("https://en.wikipedia.org/wiki/Toy_Story_3")

# Convert to t a beautifyl soup object
soup = bs(r.content)

In [58]:
info_box = soup.find(class_= "infobox vevent")
info_rows = info_box.find_all("tr")

Enumerate() method adds a counter to an iterable and returns it in a form of enumerating object. This enumerated object can then be used directly for loops or converted into a list of tuples using the list() method.

In [59]:
def get_content_value(row_data) : 
  # If row contains a list , iterate through that list and fetch all elements
  
  # Replace \xa0 with white space
  # and set strip = True which removes leading and trailing whitespaces
  
  if row_data.find("li") : 
    return [li.get_text(" ", strip = True).replace("\xa0", " ") for li in row_data.find_all("li")]
  
  else : 
    return row_data.get_text(" ", strip=True).replace("\xa0", " ")

In [60]:
movie_info = {}

for index , row in enumerate(info_rows) :
  # First will be movie title
  if index == 0 :
    movie_info['title'] = row.find("th").get_text(" ", strip = True)
  
  # Index == 1 tr is about image so skip it
  elif index == 1 :
    continue
  
  else :
    content_key = row.find("th").get_text(" ", strip = True)
    content_value = get_content_value(row.find("td"))
    
    movie_info[content_key] = content_value
    
    
print(movie_info)

{'title': 'Toy Story 3', 'Directed by': 'Lee Unkrich', 'Screenplay by': 'Michael Arndt', 'Story by': ['John Lasseter', 'Andrew Stanton', 'Lee Unkrich'], 'Produced by': 'Darla K. Anderson', 'Starring': ['Tom Hanks', 'Tim Allen', 'Joan Cusack', 'Don Rickles', 'Wallace Shawn', 'John Ratzenberger', 'Estelle Harris', 'Ned Beatty', 'Michael Keaton', 'Jodi Benson', 'John Morris'], 'Cinematography': ['Jeremy Lasky', 'Kim White'], 'Edited by': 'Ken Schretzmann', 'Music by': 'Randy Newman', 'Production companies': ['Walt Disney Pictures', 'Pixar Animation Studios'], 'Distributed by': 'Walt Disney Studios Motion Pictures', 'Release dates': ['June 12, 2010 ( 2010-06-12 ) ( Taormina Film Fest )', 'June 18, 2010 ( 2010-06-18 ) (United States)'], 'Running time': '103 minutes [1]', 'Country': 'United States', 'Language': 'English', 'Budget': '$200 million [1]', 'Box office': '$1.067 billion [1]'}

## Task#2 : Get info box for all movies

In [102]:
def get_content_value(row_data) : 
  # If row contains a list , iterate through that list and fetch all elements
  
  # Replace \xa0 with white space
  # and set strip = True which removes leading and trailing whitespaces
  
  if row_data.find("li") : 
    return [li.get_text(" ", strip = True).replace("\xa0", " ") for li in row_data.find_all("li")]
  
  # To split long strings of names together
  elif row_data.find("br") :
    return [text for text in row_data.stripped_strings]
    
  else : 
    return row_data.get_text(" ", strip=True).replace("\xa0", " ")

#To remove rferences just need to remove the "sup" tag
def clean_tags(soup) :
  for tag in soup.find_all(["sup" , "span"]) :
    tag.decompose()
    
def get_info_box(url) :   
  
  r = requests.get(url)

# Convert to t a beautifyl soup object
  soup = bs(r.content)

  contents = soup.prettify()
  
  info_box = soup.find(class_= "infobox vevent")
  info_rows = info_box.find_all("tr")
 
  clean_tags(soup)
  
  movie_info = {}

  for index , row in enumerate(info_rows) :
    # First will be movie title
    if index == 0 :
      movie_info['title'] = row.find("th").get_text(" ", strip = True)
  
    # Index == 1 tr is about image so skip it
    else :
      header = row.find("th")
      if header : 
        content_key = row.find("th").get_text(" ", strip = True)
        
        content_value = get_content_value(row.find("td"))
    
        movie_info[content_key] = content_value
    
  return movie_info

In [103]:
get_info_box("https://en.wikipedia.org/wiki/The_Nightmare_Before_Christmas")

{'title': 'The Nightmare Before Christmas',
 'Directed by': 'Henry Selick',
 'Screenplay by': 'Caroline Thompson',
 'Adaptation by': 'Michael McDowell',
 'Based on': ['Story and characters', 'by Tim Burton'],
 'Produced by': ['Tim Burton', 'Denise Di Novi'],
 'Starring': ['Danny Elfman',
  'Chris Sarandon',
  "Catherine O'Hara",
  'William Hickey',
  'Glenn Shadix',
  'Paul Reubens',
  'Ken Page',
  'Ed Ivory'],
 'Cinematography': 'Pete Kozachik',
 'Edited by': 'Stan Webb',
 'Music by': 'Danny Elfman',
 'Production companies': ['Touchstone Pictures', 'Skellington Productions'],
 'Distributed by': 'Buena Vista Pictures Distribution',
 'Release dates': ['October 13, 1993 (limited)',
  'October 29, 1993 (United States)'],
 'Running time': '76 minutes',
 'Country': 'United States',
 'Language': 'English',
 'Budget': '$24 million',
 'Box office': '$91.5 million'}

In [104]:
r = requests.get("https://en.wikipedia.org/wiki/List_of_Walt_Disney_Pictures_films")

# Convert int beautifyl soup object
soup = bs(r.content)

# Get movies that have a link/url
movies = soup.select(".wikitable.sortable i a")

base_path = "https://en.wikipedia.org/"

movie_info_list = []
for index , movie in enumerate(movies) :# 
  if index % 20 == 0:
    print(index)
  try : 
    relative_path = movie['href']
    title = movie['title']
    full_path = base_path + relative_path
    movie_info_list.append(get_info_box(full_path))
    
  except Exception as e : 
    print(movie.get_text())
    print(e)

0
20
40
Zorro the Avenger
'NoneType' object has no attribute 'find'
The Sign of Zorro
'NoneType' object has no attribute 'find'
60
80
100
120
140
160
180
200
220
240
260
280
300
320
340
360
380
400
420
440
460
480
The Beatles: Get Back â€“ The Rooftop Concert
'NoneType' object has no attribute 'find'
500
Wish
'NoneType' object has no attribute 'find_all'
Elio
'NoneType' object has no attribute 'find_all'
61
'NoneType' object has no attribute 'find_all'
All Night Long
'NoneType' object has no attribute 'find'
Big Thunder Mountain Railroad
'NoneType' object has no attribute 'find_all'
520
Keeper of the Lost Cities
'NoneType' object has no attribute 'find_all'
Muppet Man
'NoneType' object has no attribute 'find_all'
One Thousand and One Nights
'NoneType' object has no attribute 'find_all'
Shrunk
'NoneType' object has no attribute 'find'
Sister Act 3
'NoneType' object has no attribute 'find'
The Graveyard Book
'NoneType' object has no attribute 'find_all'
The Thief
'NoneType' object has no attribute 'find_all'
540
Tom Sawyer
'NoneType' object has no attribute 'find_all'
Tower of Terror
'NoneType' object has no attribute 'find_all'
Tron: Ares
'NoneType' object has no attribute 'find'
FC Barcelona
'NoneType' object has no attribute 'find_all'
Figment
'NoneType' object has no attribute 'find_all'

In [105]:
len(movie_info_list)

529

### Save / Reload Movie Data

In [30]:
import json

def save_data(title , data) : 
  with open(title , 'w' , encoding = 'utf-8') as f :
    json.dump(data , f , ensure_ascii = False , indent = 2 )

In [31]:
import json

def load_data(title) :
  with open(title , encoding = "utf-8") as f : 
    return json.load(f)

In [107]:
save_data("disney_data.json" , movie_info_list)

## Task#3 : Clean our data

In [8]:
movie_info_list = load_data("disney_data.json")

### Subtasks
- Clean up references [1]
- Convert running time into an integer
- Convert dates into datetime object
- Split up the long strings
- Convert Budget and Box office to numbers

#### Clean up references (remove [1] [2] etc)

clean_tags method created to remove the "sup" tag also "span" tag removed to clean even further

#### Split up long strings

Earlier break statements were handled with joining content with " " 

Now when we get br tag we store the elements in a list and return the list

The following elif condition was added to get_content() function

elif row_data.find("br") :
    return [text for text in row_data.stripped_strings]

#### Convert running time into an integer

In [9]:
movie_time = [movie.get('Running time', 'N/A') for movie in movie_info_list]

In [10]:
int(movie_time[0].split(" ")[0])

83

In [11]:
def minutes_to_integer(running_time) :
  if running_time == "N/A" :
    return None
  
    #If it is a list
  elif isinstance(running_time , list) :
    return int(running_time[0].split(" ")[0])
  # If it is a string
  else :
    return int(running_time.split(" ")[0])

In [123]:
for movie in movie_info_list :
  movie['Running time (int)'] = minutes_to_integer(movie.get("Running time" , "N/A"))

In [12]:
movie_info_list[-100]

{'title': 'Zootopia',
 'Directed by': ['Byron Howard', 'Rich Moore'],
 'Screenplay by': ['Jared Bush', 'Phil Johnston'],
 'Story by': ['Byron Howard',
  'Rich Moore',
  'Jared Bush',
  'Jim Reardon',
  'Josie Trinidad',
  'Phil Johnston',
  'Jennifer Lee'],
 'Produced by': 'Clark Spencer',
 'Starring': ['Ginnifer Goodwin',
  'Jason Bateman',
  'Idris Elba',
  'Jenny Slate',
  'Nate Torrence',
  'Bonnie Hunt',
  'Don Lake',
  'Tommy Chong',
  'J. K. Simmons',
  'Octavia Spencer',
  'Alan Tudyk',
  'Shakira'],
 'Cinematography': ['Nathan Warner (layout)', 'Brian Leach (lighting)'],
 'Edited by': ['Fabienne Rawley', 'Jeremy Milton'],
 'Music by': 'Michael Giacchino',
 'Production companies': ['Walt Disney Pictures',
  'Walt Disney Animation Studios'],
 'Distributed by': ['Walt Disney Studios', 'Motion Pictures'],
 'Release dates': ['February 13, 2016 (Belgium)',
  'March 4, 2016 (United States)'],
 'Running time': '108 minutes',
 'Country': 'United States',
 'Language': 'English',
 'Budget': '$150 million',
 'Box office': '$1.042 billion'}

#### Convert Budget and Box office to numbers

In [13]:
print([movie.get('Budget' , 'N/A') for movie in movie_info_list])

['$1.49 million', '$2.6 million', '$2.28 million', '$600,000', '$950,000', '$858,000', 'N/A', '$788,000', 'N/A', '$1.35 million', '$2.125 million', 'N/A', '$1.5 million', '$1.5 million', 'N/A', '$2.2 million', '$1.8 million', '$3 million', 'N/A', '$4 million', '$2 million', '$300,000', '$1.8 million', 'N/A', '$5 million', 'N/A', '$4 million', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '$700,000', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '$6 million', 'under $1 million or $1,250,000', 'N/A', '$2 million', 'N/A', 'N/A', '$2.5 million', 'N/A', 'N/A', '$4 million', '$3.6 million', 'N/A', 'N/A', 'N/A', 'N/A', '$3 million', 'N/A', '$3 million', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '$3 million', 'N/A', 'N/A', 'N/A', 'N/A', '$4.4â€“6 million', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '$4 million', 'N/A', '$5 million', 'N/A', 'N/A', 'N/A', 'N/A', '$5 million', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '$4 million', 'N/A', 'N/A', 'N/A', '$6.3 million', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '$5 million', 'N/A', 'N/A', 'N/A', 'N/A', '$8 million', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'AU$1 million', 'N/A', 'N/A', 'N/A', 'N/A', '$5 million', 'N/A', 'N/A', 'N/A', '$7.5 million', 'N/A', '$10 million', 'N/A', 'N/A', '$3.5 to 4 million', 'N/A', 'N/A', 'N/A', '$5.25 million', '$20 million', 'N/A', '$9 million', 'N/A', '$6-8 million', '$20 million', 'N/A', 'N/A', '$18 million', '$12 million', '$14 million', '$10 million', '$17 million', '$5 million', '$8 million', '$20 million', '$11 million', '$28 million', '$44 million', 'N/A', '$7.5 million', '$14 million', '$9 million', 'N/A', 'A$8.7 million', '$31 million', '$18 million', '$5 million', '$40 million', '$20 million', 'N/A', '$14 million', '60 million Norwegian Kroner (around $8.7 million in 1989)', 'N/A', '$35-40 million', '$25 million', '$15 million', '$32 million', '$14 million', '$28 million', '$12 million', 'N/A', 'N/A', '$6.5 million', '$28 million', '$17 million', '$30 million', 'N/A', '$13 million', 'N/A', 'N/A', '$5 million', '$45 million', '$31 million', 'N/A', '$22 million', '$30 million', 'N/A', '$22 million', ['$32 million', '(estimated)'], '$18 million', '$55 million', '$24 million', '$15 million', '$12 million', 'N/A', '$30 million', 'N/A', '$31 million', 'N/A', '$38 million', '$70 million', 'N/A', '$15 million', 'N/A', '$67 million', 'N/A', '$32 million', '$7 million', '$85 million', '$55 million', '$3 million', '$16 million', '$80 million', '$30 million', '$24 million', '$90 million', '$15 million', 'N/A', '$30 million', '$120 million', '$90 million', '$65 million', '$5 million', 'N/A', '$130 million', '$75â€“90 million', '$10 million', 'N/A', '$90 million', '$15 million â€“$30 million', 'N/A', '$4,000,000 (estimated)', '$127.5 million', '$80â€“85 million', '$65 million', 'N/A', 'N/A', '$30 million', '$85 million', '$100 million', '$23 million', 'N/A', '$90â€“120 million', '$26 million', '$25 million', '$115 million', 'N/A', '$33 million', '$20 million', '$5 million', 'N/A', '$22 million', '$80 million', '$35 million', '$19.2 million', '$15 million', '$65 million', '$140 million', 'N/A', '$20 million', '$12 million', '$46 million', '$13 million', '$20 million', '$17 million', '$94 million', '$140 million', '$26 million', 'N/A', 'N/A', '$46 million', '$90 million', 'N/A', '$10 million', '$28 million', 'N/A', '$15 million', 'N/A', '$110 million', 'N/A', '$110 million', 'N/A', '$45 million', 'N/A', '$92â€“145 million', 'N/A', '$100 million', 'N/A', 'N/A', '$20 million', '$56 million', '$25 million', 'N/A', '$50 million', ['Â¥', '2.4 billion', 'US$24 million'], '$35 million', '$35 million', 'N/A', 'N/A', '$25 million', '$150 million', '$180 million', 'N/A', '$30 million', '$1 million', 'N/A', '$40 million', '$50 million', '$80 million', '$120 million', 'N/A', '$225 million', '$30 million', 'N/A', '$24 million', 'N/A', 'N/A', '$8 million', '$17 million', '$150 million', '$300 million', '$150 million', 'N/A', '$25 million', 'N/A', '$22 million', '$85 million', '$130 million', '$7 million', '$25 million', '$225 million', '$180 million', 'N/A', '$20 million', 'N/A', '$11 million', 'N/A', '$50 million', '$150 million', '$80 million', 'N/A', '$50 million', '$30 million', '$47 million', 'N/A', '$175 million', 'N/A', '$150 million', ['Â¥', '3.4 billion', '(', 'US$', '34 million)'], 'N/A', '$30â€”$35 million', '$8 million ( â‚½ 350 million)', '$175â€“200 million', '$35 million', '$105 million', '$150 â€“$200 million', '$80 million', '$150â€“200 million', '$200 million', '$150 million', '$22 million', 'N/A', '$30â€”$35 million', '$35 million', 'N/A', '$260 million', '$170 million', '', 'N/A', 'N/A', '$150 million', 'N/A', '$5 million', '$8 million', ['$410.6 million (gross)', '$378.5 million (net)'], '$200 million', '$30 million', 'N/A', '$45 million', 'N/A', '$23 million', ['$306.6 million (gross)', '$263.7 million (net)'], '$5 million', 'N/A', '$185 million', '$25 million', 'N/A', '$39 million', '$30â€”35 million', '$165 million', '$200 million', 'N/A', '$200 million', '$225â€“250 million', '$50 million', 'N/A', '$150 million', '$35 million', '$50 million', 'N/A', '$5 million', '$25 million', '$180â€“263 million', '$50 million', '(US$2.9 million)', '$28 million', '$165 million', '$50 million', '$17 million', 'N/A', '$84.21â€“95 million', '$5â€“10 million', '$180â€“190 million', '$175 million', '', '$175â€“200 million', '$70â€“80 million', '$150 million', '$175â€“177 million', 'N/A', '$170 million', '$200 million', '$140 million', '$65 million', '$15 million', '$150â€“175 million', '', '$8 million', '$160â€“255 million', '$5â€“10 million', '$230â€“320 million', '$175 million', 'N/A', '131 crore', ['~$8 million', 'â‚½', '370 million'], '$175â€“225 million', '$100â€“130 million', '$200 million', '$65-70 million', '$120â€“133 million', '$175 million', '$130 million', '$170 million', 'N/A', '$183 million', '$200 million', '$250â€“260 million', '$185 million', '$60 million', 'N/A', '$150 million', '$40 million', '$42 million', '$175â€“200 million', 'N/A', 'N/A', 'N/A', '$125 million', '$12.5 million (stage production)', 'N/A', '$24 million', 'N/A', '$200 million', 'N/A', '$26 million', '$150 million', 'â‚½650 million', 'N/A', '$100 million+', '$100â€“200 million', 'N/A', '$200 million', '$120â€“150 million', 'N/A', 'â‚½454 million', 'N/A', '$175 million', 'N/A', '$36 million', 'N/A', '~$70 million', 'N/A', '$200 million', 'N/A', '$150 million', '$40 million', 'N/A', '$135â€“180 million', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', 'N/A', '$175 million', '$250â€“260 million', 'N/A', 'N/A', '$28 million', '$858,000', '$53.4 million', 'N/A', '$85 million', '$70 million', '$75â€“90 million', '$80 million', '$130 million', 'N/A', '$5 million', '$18 million or $25 million', 'N/A', '$4 million', '$3 million', '$11â€”15 million', 'N/A', '$35-40 million', 'N/A']

In [17]:
import re

amounts = r"thousand|million|billion"
number = r"\d+(,\d{3})*\.*\d*"

word_re = rf"\${number}(-|\sto\s|-)?({number})?\s({amounts})"
value_re = rf"\${number}"


# money_convesion("$12.2 million") = 12200000 -> word syntax
# money_conversion("$790,000") = 79000 -> value syntax

def word_to_value(word) :
  value_dict = {"thousand" : 1000 , "million" : 1000000 , "billion" : 1000000000}
  return value_dict[word]

def parse_word_syntax(string) :
  value_string = re.search(number , string).group()
  value = float(value_string.replace("," , ""))
  word = re.search(amounts , string).group()
  word_value = word_to_value(word)
  return value * word_value
  
def parse_value_syntax(string) :
  value_string = re.search(number , string).group()
  value = float(value_string.replace("," , ""))
  return value

def money_conversion(money) :
  
  if isinstance(money,list) :
    money = money[0]
  
  value_syntax = re.search(value_re , money)
  word_syntax = re.search(word_re , money)
  
  if word_syntax :
    return parse_word_syntax(word_syntax.group())

  elif value_syntax :
    return parse_value_syntax(value_syntax.group())

In [18]:
for movie in movie_info_list :
  movie['Budget (float)'] = money_conversion(movie.get('Budget' , 'N/A'))
  movie['Box office (float)'] = money_conversion(movie.get('Box office' , 'N/A'))

In [20]:
movie_info_list[286]

{'title': 'Miracle',
 'Directed by': "Gavin O'Connor",
 'Written by': ['Eric Guggenheim', 'Mike Rich'],
 'Produced by': ['Mark Ciardi',
  'Gordon Gray',
  'Ross Greenburg',
  'Justis Greene',
  'Jon Mone',
  "Greg O'Connor"],
 'Starring': ['Kurt Russell', 'Patricia Clarkson', 'Noah Emmerich'],
 'Cinematography': 'Dan Stoloff',
 'Edited by': ['John Gilroy', 'Daric Loo'],
 'Music by': 'Mark Isham',
 'Production companies': ['Walt Disney Pictures', 'Mayhem Pictures'],
 'Distributed by': 'Buena Vista Pictures Distribution',
 'Release date': ['February 20, 2004'],
 'Running time': '136 minutes',
 'Country': 'United States',
 'Language': 'English',
 'Budget': '$28 million',
 'Box office': '$64.5 million',
 'Budget (float)': 28000000.0,
 'Box office (float)': 64500000.0}

#### Convert Dates into datetime

In [32]:
# June 28 , 1950
from datetime import datetime

dates = [movie.get('Release date' , 'N/A') for movie in movie_info_list]

def clean_date(date) :
  return date.split("(")[0].strip()

def date_conversion(date) :
  if isinstance(date , list) :
    date = date[0]
  
  if date == "N/A" :
    return None
  
  date_str = clean_date(date)
  print(date_str)

  fmts= ["%B %d, %Y" , "%d %B %Y"]
  
  for fmt in fmts :
    try : 
      return datetime.strptime(date_str, fmt)
    except : 
      pass
  
  return None

In [33]:
for movie in movie_info_list :
  movie['Release date (datetime)'] = date_conversion(movie.get('Release date' , 'N/A'))

November 13, 1940
June 27, 1941
July 17, 1943
September 27, 1947
May 27, 1948
October 5, 1949
February 5, 1953
July 23, 1953
November 10, 1953
August 17, 1954
December 23, 1954
May 25, 1955
June 22, 1955
September 14, 1955
December 22, 1955
June 8, 1956
July 18, 1956
September 4, 1956
December 20, 1956
June 19, 1957
August 28, 1957
December 25, 1957
July 8, 1958
August 12, 1958
December 25, 1958
January 29, 1959
March 19, 1959
November 10, 1959
January 21, 1960
February 24, 1960
May 19, 1960
November 1, 1960
December 21, 1960
January 25, 1961
March 16, 1961
June 21, 1961
July 12, 1961
July 17, 1961
December 14, 1961
April 5, 1962
May 17, 1962
June 6, 1962
September 26, 1962
November 7, 1962
January 16, 1963
March 29, 1963
June 1, 1963
July 7, 1963
November 20, 1963
March 12, 1964
February 11, 1964
July 2, 1964
November 10, 1964
December 18, 1964
August 18, 1965
December 2, 1965
October 1, 1966
December 1, 1966
February 8, 1967
June 15, 1967
July 12, 1967
October 18, 1967
October 19, 1967
February 8, 1968
March 21, 1968
June 26, 1968
December 3, 1968
March 21, 1969
June 11, 1969
November 28, 1969
February 11, 1970
July 1, 1970
December 15, 1970
March 17, 1971
June 22, 1971
June 30, 1971
October 7, 1971
March 22, 1972
July 12, 1972
July 5, 1972
October 18, 1972
December 22, 1972
February 1, 1973
March 23, 1973
June 20, 1973
November 8, 1973
December 14, 1973
June 6, 1974
July 31, 1974
August 1, 1974
December 20, 1974
February 6, 1975
March 21, 1975
July 1, 1975
July 9, 1975
October 8, 1975
1948â€“1960
December 25, 1975
February 11, 1976
July 1, 1976
July 7, 1976
December 16, 1976
March 11, 1977
June 20, 1977
June 22, 1977
June 24, 1977
November 3, 1977
December 16, 1977
March 10, 1978
June 30, 1978
July 5, 1978
February 9, 1979
June 27, 1979
February 8, 1980
June 27, 1980
July 9, 1980
February 11, 1981
March 20, 1981
June 26, 1981
July 10, 1981
August 7, 1981
February 5, 1982
July 9, 1982
July 30, 1982
March 11, 1983
April 29, 1983
June 21, 1985
July 24, 1985
September 27, 1985
November 22, 1985
July 2, 1986
August 1, 1986
June 5, 1987
November 18, 1988
June 23, 1989
August 18, 1989
November 17, 1989
August 3, 1990
November 16, 1990
January 18, 1991
May 24, 1991
June 21, 1991
April 10, 1992
July 17, 1992
October 2, 1992
November 11, 1992
December 11, 1992
February 3, 1993
March 12, 1993
April 2, 1993
July 16, 1993
October 1, 1993
November 12, 1993
January 14, 1994
February 11, 1994
March 25, 1994
April 14, 1994
May 20, 1994
June 15, 1994
July 15, 1994
October 28, 1994
December 25, 1994
February 17, 1995
March 3, 1995
March 24, 1995
April 7, 1995
June 16, 1995
July 28, 1995
August 11, 1995
September 27, 1995
December 22, 1995
February 16, 1996
March 8, 1996
August 13, 1996
August 30, 1996
October 4, 1996
February 14, 1997
March 18, 1997
June 13, 1997
July 16, 1997
August 1, 1997
October 10, 1997
December 25, 1997
March 27, 1998
July 29, 1998
September 29, 1998
November 13, 1998
December 25, 1998
February 12, 1999
March 26, 1999
July 23, 1999
November 9, 1999
February 11, 2000
February 29, 2000
March 10, 2000
May 19, 2000
July 7, 2000
August 8, 2000
September 19, 2000
September 29, 2000
November 22, 2000
February 27, 2001
October 5, 2001
November 3, 2001
January 18, 2002
February 26, 2002
March 19, 2002
March 29, 2002
20 July 2001
October 11, 2002
January 21, 2003
February 14, 2003
March 11, 2003
April 18, 2003
May 2, 2003
August 26, 2003
October 21, 2003
November 1, 2003
November 26, 2003
December 25, 2003
January 16, 2004
February 20, 2004
February 10, 2004
February 20, 2004
March 9, 2004
April 22, 2004
June 16, 2004
July 2, 2004
August 11, 2004
August 17, 2004
November 9, 2004
November 19, 2004
January 28, 2005
February 11, 2005
March 4, 2005
March 18, 2005
June 14, 2005
July 29, 2005
August 30, 2005
September 13, 2005
September 30, 2005
December 13, 2005
January 13, 2006
January 27, 2006
February 17, 2006
March 10, 2006
April 14, 2006
August 25, 2006
August 29, 2006
November 3, 2006
December 12, 2006
February 6, 2007
February 16, 2007
August 3, 2007
August 28, 2007
December 21, 2007
February 1, 2008
March 7, 2008
26 August 2008
October 17, 2008
October 28, 2008
December 25, 2008
February 27, 2009
April 10, 2009
July 24, 2009
July 19, 2008
2009
October 29, 2009
November 25, 2009
July 29, 2006
8 October 2010
14 January 2011
February 1, 2011
17 February 2011
22 April 2011
April 29, 2011
September 20, 2011
January 31, 2012
17 July 2010
25 May 2012
August 15, 2012
September 18, 2012
August 27, 2013
April 18, 2014
19 September 2014
April 17, 2015
19 June 2015
24 June 2005
June 30, 2017
14 July 2017
October 29, 2017
April 17, 2019
October 18, 2019
November 12, 2019
November 12, 2019
December 20, 2019
March 13, 2020
April 3, 2020
June 12, 2020
July 3, 2020
July 31, 2020
August 14, 2020
August 21, 2020
December 4, 2020
December 11, 2020
February 19, 2021
March 5, 2021
December 3, 2021
23 December 2021
January 28, 2022
April 22, 2022
June 24, 2022
September 8, 2022
September 30, 2022
December 2, 2022
December 9, 2022
May 26, 2023
June 16, 2023
August 11, 2023
March 22, 2024
2023
2023
1950â€“present
June 13, 1997
July 23, 1999
December 21, 2007
November 8, 1973
June 6, 1986
November 25, 1987
June 21, 1991

In [34]:
movie_info_list[29]

{'title': 'The Great Locomotive Chase',
 'Directed by': 'Francis D. Lyon',
 'Written by': 'Lawrence Edward Watkin',
 'Produced by': ['Lawrence Edward Watkin', 'Walt Disney'],
 'Starring': ['Fess Parker',
  'Jeffrey Hunter',
  'John Lupton',
  'Jeff York',
  'Slim Pickens'],
 'Cinematography': 'Charles Boyle',
 'Edited by': 'Ellsworth Hoagland',
 'Music by': 'Paul J. Smith',
 'Production company': 'Walt Disney Productions',
 'Distributed by': 'Buena Vista Distribution',
 'Release date': 'June 8, 1956',
 'Running time': '85 minutes',
 'Country': 'United States',
 'Language': 'English',
 'Box office': '$1.7 million (US)',
 'Budget (float)': None,
 'Box office (float)': 1700000.0,
 'Release date (datetime)': datetime.datetime(1956, 6, 8, 0, 0)}

## Save data

In [25]:
import pickle

def save_data_pickle(name , data) : 
  with open(name , 'wb') as f :
    pickle.dump(data , f)

In [2]:
import pickle

def load_data_pickle(name) : 
  with open(name , 'rb') as f :
    return pickle.load(f)

In [37]:
save_data_pickle("disney_movie_data_cleaned_more.pickle" , movie_info_list)

In [38]:
a = load_data_pickle("disney_movie_data_cleaned_more.pickle")

In [39]:
a[5]

{'title': 'Bambi',
 'Directed by': ['Supervising director',
  'David Hand',
  'Sequence directors',
  'James Algar',
  'Samuel Armstrong',
  'Graham Heid',
  'Bill Roberts',
  'Paul Satterfield',
  'Norman Wright'],
 'Story by': ['Story direction',
  'Perce Pearce',
  'Story adaptation',
  'Larry Morey',
  'Story development',
  'Vernon Stallings',
  'Melvin Shaw',
  'Carl Fallberg',
  'Chuck Couch',
  'Ralph Wright'],
 'Based on': ['Bambi, a Life in the Woods', 'by', 'Felix Salten'],
 'Produced by': 'Walt Disney',
 'Starring': 'see below',
 'Music by': ['Frank Churchill', 'Edward H. Plumb'],
 'Production company': 'Walt Disney Productions',
 'Distributed by': 'RKO Radio Pictures',
 'Release dates': ['August 9, 1942 ( London )',
  'August 21, 1942 (United States)'],
 'Running time': '70 minutes',
 'Country': 'United States',
 'Language': 'English',
 'Budget': '$858,000',
 'Box office': '$267.4 million',
 'Budget (float)': 858000.0,
 'Box office (float)': 267399999.99999997,
 'Release date (datetime)': None}

In [40]:
a == movie_info_list

True

## Attach IMDB / Rotten Tomatoes / Metascore Scores

In [3]:
movie_info_list = load_data_pickle("disney_movie_data_cleaned_more.pickle")

In [4]:
#http://www.omdbapi.com/?apikey=[yourkey]&

In [20]:
import requests
import urllib
import os

def get_omdb_info(title) : 
  base_url = "http://www.omdbapi.com/?"
  parameters = {'i' : 'tt3896198' ,'apikey' : os.environ['OMDB_API_KEY'] , 't' : title}
  params_encoded = urllib.parse.urlencode(parameters)
  full_url = base_url + params_encoded
  return requests.get(full_url).json()

def get_rotten_tomato_score(omdb_info) :
  ratings = omdb_info.get('Ratings' , [])
  for rating in ratings : 
    if rating['Source'] == 'Rotten Tomatoes' :
      return rating['Value']
  return None

In [22]:
for movie in movie_info_list :
  title = movie['title']
  omdb_info = get_omdb_info(title)
  movie['imdb'] = omdb_info.get('imdbRating' , None)
  movie['metascore'] = omdb_info.get('Metascore' , None)
  movie['rotten_tomatoes'] = get_rotten_tomato_score(omdb_info)

In [23]:
movie_info_list[-50]

{'title': 'Flora & Ulysses',
 'Directed by': 'Lena Khan',
 'Screenplay by': 'Brad Copeland',
 'Based on': ['Flora & Ulysses', 'by', 'Kate DiCamillo'],
 'Produced by': 'Gil Netter',
 'Starring': ['Matilda Lawler',
  'Alyson Hannigan',
  'Ben Schwartz',
  'Anna Deavere Smith',
  'Danny Pudi',
  'Benjamin Evan Ainsworth',
  'Janeane Garofalo',
  'Kate Micucci'],
 'Cinematography': 'Andrew Dunn',
 'Edited by': 'Jamie Gross',
 'Music by': 'Jake Monaco',
 'Production companies': ['Walt Disney Pictures', 'Netter Productions'],
 'Distributed by': 'Disney+',
 'Release date': ['February 19, 2021'],
 'Running time': '95 minutes',
 'Country': 'United States',
 'Language': 'English',
 'Budget (float)': None,
 'Box office (float)': None,
 'Release date (datetime)': datetime.datetime(2021, 2, 19, 0, 0),
 'imdb': '6.2',
 'metascore': '62',
 'rotten_tomatoes': None}

In [26]:
save_data_pickle('disney_movie_data_final.pickle'  , movie_info_list)

## Task#5 : Save Data as JSON and CSV

In [27]:
# Replace datetime with string

movie_info_copy = [movie.copy() for movie in movie_info_list]

In [28]:
for movie in movie_info_copy : 
  current_date = movie['Release date (datetime)']
  if current_date :
    movie['Release date (datetime)'] = current_date.strftime("%B %d, %Y")
  else :
    movie['Release date (datetime)'] = None

In [32]:
save_data('disney_data_final.json' , movie_info_copy)

### Convert Data to CSV

In [33]:
import pandas as pd

df = pd.DataFrame(movie_info_list)

In [35]:
df.head(100)

                              title  ... Awards
0   Snow White and the Seven Dwarfs  ...    NaN
1                         Pinocchio  ...    NaN
2                          Fantasia  ...    NaN
3              The Reluctant Dragon  ...    NaN
4                             Dumbo  ...    NaN
..                              ...  ...    ...
95                     The Boatniks  ...    NaN
96                 The Wild Country  ...    NaN
97                   The Aristocats  ...    NaN
98           The Barefoot Executive  ...    NaN
99                  Scandalous John  ...    NaN

[100 rows x 44 columns]

In [36]:
df.shape

(529, 44)

In [37]:
df.to_csv("disney_movie_data_final.csv")

In [38]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 529 entries, 0 to 528
Data columns (total 44 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   title                    529 non-null    object
 1   Directed by              525 non-null    object
 2   Written by               218 non-null    object
 3   Based on                 290 non-null    object
 4   Produced by              516 non-null    object
 5   Starring                 491 non-null    object
 6   Music by                 519 non-null    object
 7   Production company       209 non-null    object
 8   Distributed by           527 non-null    object
 9   Release dates            194 non-null    object
 10  Running time             514 non-null    object
 11  Country                  465 non-null    object
 12  Language                 505 non-null    object
 13  Budget                   327 non-null    object
 14  Box office               406 non-null    object
 15  Budget (float)           319 non-null    float64
 16  Box office (float)       395 non-null    float64
 17  Release date (datetime)  325 non-null    datetime64[ns]
 18  imdb                     513 non-null    object
 19  metascore                513 non-null    object
 20  rotten_tomatoes          389 non-null    object
 21  Story by                 178 non-null    object
 22  Narrated by              63 non-null     object
 23  Cinematography           399 non-null    object
 24  Release date             330 non-null    object
 25  Edited by                485 non-null    object
 26  Languages                22 non-null     object
 27  Screenplay by            263 non-null    object
 28  Countries                58 non-null     object
 29  Color process            7 non-null      object
 30  Production companies     317 non-null    object
 31  Japanese                 5 non-null      object
 32  Hepburn                  5 non-null      object
 33  Adaptation by            1 non-null      object
 34  Traditional              2 non-null      object
 35  Simplified               2 non-null      object
 36  Original title           1 non-null      object
 37  Layouts by               2 non-null      object
 38  Music                    2 non-null      object
 39  Lyrics                   2 non-null      object
 40  Book                     2 non-null      object
 41  Basis                    2 non-null      object
 42  Productions              2 non-null      object
 43  Awards                   2 non-null      object
dtypes: datetime64[ns](1), float64(2), object(41)
memory usage: 182.0+ KB